// Cohort-facing Intel preview.
//
// Audience boundary:
// - Safe for the Shape Rotator OS cohort-facing app.
// - Grounded only in public/cohort-facing project records, public links, and
//   the sanitized relationship map bundled with this app.
// - Do not add private provenance here. Organizer-only reads belong outside
//   this UI.
export const INTEL_SIGNALS = [
  {
    id: "move-tee-trust-map",
    tier: "grounded",
    kind: "cross-domain",
    title: "TEE teams should make their trust promises comparable",
    entities: [
      "project:signalstack",
      "project:teesql",
      "project:dealproof",
      "project:trustless-tee",
      "project:conclave",
    ],
    displayEntities: [
      "SignalStack",
      "TeeSQL",
      "DealProof",
      "Trustless TEE",
      "Conclave",
    ],
    claim: "Several cohort projects ask users to trust a machine-verifiable boundary, but each sells a different promise: private inference, confidential storage, dual-agent contracts, open trust roots, or confidential negotiation.",
    shapeRotation: "Rotate the TEE cluster from parallel technical pitches into one shared trust map that any cohort member can inspect and challenge.",
    chain: [
      "the public project records show multiple TEE, attestation, and confidential-compute teams in the same cohort",
      "their user promises differ enough that the same word, trust, may mean different things in each demo",
      "a shared map helps teams see complements and gaps without ranking one project over another",
      "therefore: the cohort-facing move is to make each team name its user, trusted boundary, failure mode, and visible proof",
    ],
    coordinatorMove: "Run a public trust-map session where each TEE-adjacent team fills one row: user, trusted boundary, failure mode, proof shown to the user.",
    introduction: "Stage SignalStack, TeeSQL, DealProof, Trustless TEE, and Conclave around a shared whiteboard instead of a pitch round.",
    watchFor: "If two teams describe the same user promise with different mechanisms, that is a collaboration path. If a team cannot name the proof a user sees, that is a product-clarity gap.",
    limits: "Limit: this is a public project-record synthesis, not a verdict on security quality. Technical claims still need team review and concrete demos.",
    sourceReceipts: [
      "Cohort-facing project records",
      "Public project links and demos",
      "Sanitized relationship map",
    ],
  },
  {
    id: "move-agent-toolchain-dogfood",
    tier: "grounded",
    kind: "catalytic-pairing",
    title: "Agent-infra teams can prove value by becoming each other's workflow",
    entities: [
      "project:jjhub",
      "project:contexto",
      "project:bitrouter",
      "project:searxng-wth-frnds",
      "project:tinycloud",
    ],
    displayEntities: [
      "JJHub",
      "Contexto",
      "Bitrouter",
      "searxng-wth-frnds",
      "TinyCloud",
    ],
    claim: "The cohort already contains agent runtime, memory, routing, local search, and user-owned cloud pieces. The public opportunity is to make one working loop across those pieces instead of letting each team demo in isolation.",
    shapeRotation: "Rotate agent tooling from separate product surfaces into one cohort dogfood loop: search, context, route, run, review, and persist.",
    chain: [
      "public team records identify several projects working on agent infrastructure and developer workflow",
      "each project has a plausible standalone surface, but the cohort can test integration faster than an outside customer can",
      "a real shared workflow is more informative than another abstract platform explanation",
      "therefore: pick one cohort task and make the agent-infra teams wire their public pieces together around it",
    ],
    coordinatorMove: "Ask the agent-infra teams to pick one boring recurring cohort task and make a live cross-project workflow that completes it end to end.",
    introduction: "Stage JJHub, Contexto, Bitrouter, searxng-wth-frnds, and TinyCloud around a single workflow owner and a concrete success test.",
    watchFor: "If the loop works once with human review and repeatable handoff, the stack becomes legible. If every project still needs its own separate demo, the integration story is not ready.",
    limits: "Limit: this is a public integration hypothesis from project records. It should not imply any team is obligated to merge roadmaps.",
    sourceReceipts: [
      "Cohort-facing project records",
      "Public repo and website links",
      "Sanitized relationship map",
    ],
  },
  {
    id: "move-health-data-pilot",
    tier: "grounded",
    kind: "convergence",
    title: "Health and regulated-data teams need one shared pilot proof format",
    entities: [
      "project:prova",
      "project:wikigen",
      "project:signalstack",
      "project:teesql",
    ],
    displayEntities: [
      "Prova",
      "WikiGen",
      "SignalStack",
      "TeeSQL",
    ],
    claim: "Healthcare, bio-data, private messaging, and confidential database projects all face the same public-facing challenge: a useful demo must also explain what data is protected, who can inspect the proof, and what risk remains.",
    shapeRotation: "Rotate regulated-data demos from feature tours into proof cards: user, data touched, protected boundary, proof artifact, next pilot ask.",
    chain: [
      "public records show multiple cohort projects touching healthcare, private data, or regulated workflows",
      "these teams need trust language that non-TEE users can understand without weakening the technical claim",
      "a shared pilot proof format makes comparison and collaboration easier across very different products",
      "therefore: the cohort should give these teams one public-safe template for explaining pilot readiness",
    ],
    coordinatorMove: "Ask Prova, WikiGen, SignalStack, and TeeSQL to each fill one pilot proof template before their next demo.",
    introduction: "Stage the teams with one non-technical reviewer who asks only what data moves, what stays protected, and what proof the user sees.",
    watchFor: "If a reviewer can explain the protected workflow back in plain language, the pilot story is working. If the explanation depends on insider terms, it needs another pass.",
    limits: "Limit: this is a demo-readiness pattern from public project records, not a compliance or security review.",
    sourceReceipts: [
      "Cohort-facing project records",
      "Public project links and demos",
      "Sanitized relationship map",
    ],
  },
  {
    id: "move-identity-without-exposure",
    tier: "grounded",
    kind: "multi-hop",
    title: "Identity and privacy projects can share the same user story",
    entities: [
      "project:pramaana",
      "project:crossroads",
      "project:dcnet",
      "project:signalstack",
    ],
    displayEntities: [
      "Pramaana",
      "Crossroads",
      "DCNet",
      "SignalStack",
    ],
    claim: "Several public project records circle the same user need from different angles: prove, route, speak, or sign without exposing more than necessary.",
    shapeRotation: "Rotate privacy projects from mechanism-first demos into one shared user story about proving enough while revealing less.",
    chain: [
      "Pramaana, Crossroads, DCNet, and SignalStack each work near identity, signing, broadcast, privacy, or private assistance",
      "the mechanisms differ, but the user story can be shared across projects",
      "a shared story helps the cohort see when these are complements rather than unrelated privacy demos",
      "therefore: test one public-safe scenario that needs identity, routing, communication, and selective disclosure",
    ],
    coordinatorMove: "Ask the identity and privacy teams to write one scenario in which a user proves eligibility, routes an action, and communicates privately.",
    introduction: "Stage Pramaana, Crossroads, DCNet, and SignalStack around the same user story before discussing mechanisms.",
    watchFor: "If the projects can divide the scenario cleanly, collaboration is plausible. If the story breaks at the user-language layer, the demos are still too mechanism-first.",
    limits: "Limit: this is a public product-framing exercise. It should not claim protocol compatibility until teams validate the technical interfaces.",
    sourceReceipts: [
      "Cohort-facing project records",
      "Public project links",
      "Sanitized relationship map",
    ],
  },
  {
    id: "move-demo-feedback-loop",
    tier: "grounded",
    kind: "catalytic-pairing",
    title: "Communication and creative tools can form a live demo feedback loop",
    entities: [
      "project:etherea",
      "project:elocute",
      "project:shake",
    ],
    displayEntities: [
      "Etherea",
      "Elocute",
      "Shake",
    ],
    claim: "Etherea, Elocute, and Shake all sit near the human surface of the cohort: speaking, performance, presence, memory, and relationship cues. Their public-safe overlap is live feedback, not infrastructure.",
    shapeRotation: "Rotate these projects from separate experience tools into a small live-loop: practice, perform, remember, and improve.",
    chain: [
      "public project records place these teams near communication, creative expression, or relationship tracking",
      "their value becomes easier to understand when someone uses them in a live context",
      "a cohort demo can test whether the tools strengthen one another without exposing private participant data",
      "therefore: run a short opt-in public demo loop with synthetic or volunteered material only",
    ],
    coordinatorMove: "Run a 20-minute opt-in demo: one person practices a short pitch, one tool creates the stage surface, one tool captures follow-up cues.",
    introduction: "Stage Etherea, Elocute, and Shake around an explicit opt-in demo with synthetic or volunteered content.",
    watchFor: "If the loop makes the speaker better and the audience understands each tool's role, the collaboration is real. If it feels like three separate demos, keep them separate.",
    limits: "Limit: use only opt-in or synthetic content. This signal is about public demo design, not private social inference.",
    sourceReceipts: [
      "Cohort-facing project records",
      "Public project links",
      "Sanitized relationship map",
    ],
  },
  {
    id: "move-market-infra-pilot",
    tier: "grounded",
    kind: "tension-map",
    title: "Market-infra teams should name the first external pilot surface",
    entities: [
      "project:daedalus",
      "project:bitrouter",
      "project:crossroads",
    ],
    displayEntities: [
      "Daedalus",
      "Bitrouter",
      "Crossroads",
    ],
    claim: "Daedalus, Bitrouter, and Crossroads each touch markets, routing, or asset movement. The public coordination question is not which is most sophisticated; it is which first pilot surface can produce a real external signal fastest.",
    shapeRotation: "Rotate market-infra discussion from architecture comparison into pilot-surface selection.",
    chain: [
      "public project records show teams working around prediction markets, routing, payments, wallets, or cross-chain flows",
      "these projects need different buyers and proof metrics even when their technical vocabulary overlaps",
      "the cohort can help by separating pilot users, proof metrics, and intro requests",
      "therefore: each team should leave with one named pilot surface and one falsifiable next milestone",
    ],
    coordinatorMove: "Ask each market-infra team for one pilot user, one proof metric, and one intro request; do not let architecture discussion replace the pilot decision.",
    introduction: "Stage Daedalus, Bitrouter, and Crossroads with a facilitator who keeps the conversation on first pilot surface.",
    watchFor: "If a team can name a user and proof metric, the next intro is actionable. If it only names a mechanism, the pilot path is still unclear.",
    limits: "Limit: this is public GTM scaffolding from project records. It does not assess technical depth or investor readiness.",
    sourceReceipts: [
      "Cohort-facing project records",
      "Public project links and repos",
      "Sanitized relationship map",
    ],
  },
];
